function out1 = get_jac_com(in1)
%GET_JAC_COM
%    OUT1 = GET_JAC_COM(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    30-Nov-2023 14:58:03

q1 = in1(3,:);
q2 = in1(4,:);
t2 = q1+q2;
t3 = cos(t2);
t4 = sin(t2);
t5 = t3./4.8e+2;
t6 = t4./4.8e+2;
t7 = -t6;
out1 = reshape([1.0,0.0,0.0,1.0,t7-sin(q1)./1.6e+2,t5+cos(q1)./1.6e+2,t7,t5],[2,4]);
