function W_X_F = get_W_X_F(in1)
%get_W_X_F
%    W_X_F = get_W_X_F(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    30-Nov-2023 14:58:03

q1 = in1(3,:);
q2 = in1(4,:);
x = in1(1,:);
y = in1(2,:);
t2 = cos(q1);
t3 = cos(q2);
t4 = sin(q1);
t5 = sin(q2);
t6 = t2.*t3;
t7 = t2.*t5;
t8 = t3.*t4;
t9 = t4.*t5;
t10 = t3./2.0;
t11 = -t9;
t12 = t10+1.0./2.0;
t13 = t6+t11;
W_X_F = reshape([t13,t7+t8,0.0,0.0,-t7-t8,t13,0.0,0.0,0.0,0.0,1.0,0.0,t2./2.0+t6./2.0+t11+x+t2.*t12,t4./2.0+t7+t8./2.0+y+t4.*t12,0.0,1.0],[4,4]);
