function r_F_pol = get_r_F_pol(in1)
%get_r_F_pol
%    r_F_pol = get_r_F_pol(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    30-Nov-2023 14:58:03

q1 = in1(3,:);
q2 = in1(4,:);
t2 = q1+q2;
r_F_pol = [sqrt(2.0).*sqrt(cos(q2)+1.0);atan2(sin(q1)+sin(t2),cos(q1)+cos(t2))];
