function n = get_n(in1,in2)
%GET_N
%    N = GET_N(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    30-Nov-2023 14:58:04

dq1 = in2(3,:);
dq2 = in2(4,:);
dx = in2(1,:);
dy = in2(2,:);
q1 = in1(3,:);
q2 = in1(4,:);
t2 = cos(q1);
t3 = sin(q2);
t4 = q1+q2;
t5 = cos(t4);
t6 = sin(t4);
t7 = t5.*2.4525e-1;
n = [dq1.*dx.*(t2.*3.0+t5.*2.0).*(-1.0./4.0e+1)-(dq2.*dx.*t5)./2.0e+1;dq2.*dy.*t6.*(-1.0./2.0e+1)-(dq1.*dy.*(t6.*2.0+sin(q1).*3.0))./4.0e+1+1.1772e+2;t2.*7.3575e-1+t7-(dq1.^2.*t3)./4.0e+1-(dq1.*dq2.*t3)./2.0e+1;t7+(dq1.*dq2.*t3)./4.0e+1];
