function E_sys_d = get_E_sys_d(in1,H_d)
%get_E_sys_d
%    E_sys_d = get_E_sys_d(IN1,H_d)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    26-Feb-2023 00:04:53

q1 = in1(3,:);
q2 = in1(4,:);
t2 = sin(q1);
t3 = pi.*(4.0./9.0);
t4 = pi.*(7.0./3.6e+1);
t5 = cos(t3);
t6 = cos(t4);
t7 = sin(t3);
t8 = sin(t4);
t9 = t5./2.0;
t10 = t9-1.0./2.0;
E_sys_d = t2.*4.905e-1+conj(H_d).*1.1772e+2+cos(q1).*sin(q2).*2.4525e-1+t2.*(cos(q2)./2.0+1.0./2.0).*4.905e-1+sqrt((t6.*(-1.0./2.0)+t6.*t9+t7.*t8+t6.*t10).^2+(t8./2.0-(t5.*t8)./2.0+t6.*t7-t8.*t10).^2).*1.1772e+2;
