function l_rest = get_l_rest
%GET_L_REST
%    L_REST = GET_L_REST

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    30-Nov-2023 14:58:03

t2 = pi.*(4.0./9.0);
t3 = pi.*(7.0./3.6e+1);
t4 = cos(t2);
t5 = cos(t3);
t6 = sin(t2);
t7 = sin(t3);
t8 = t4./2.0;
t9 = t8-1.0./2.0;
l_rest = sqrt((t5.*(-1.0./2.0)+t5.*t8+t6.*t7+t5.*t9).^2+(t7./2.0-(t4.*t7)./2.0+t5.*t6-t7.*t9).^2);
