function C = get_Coriolis(in1,in2)
%get_Coriolis
%    C = get_Coriolis(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    30-Nov-2023 14:58:04

dq1 = in2(3,:);
dq2 = in2(4,:);
dx = in2(1,:);
dy = in2(2,:);
q1 = in1(3,:);
q2 = in1(4,:);
t2 = sin(q2);
t3 = q1+q2;
t4 = cos(t3);
t5 = sin(t3);
C = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,dx.*(t4.*2.0+cos(q1).*3.0).*(-1.0./4.0e+1),dy.*(t5.*2.0+sin(q1).*3.0).*(-1.0./4.0e+1),dq1.*t2.*(-1.0./4.0e+1),(dq2.*t2)./4.0e+1,dx.*t4.*(-1.0./2.0e+1),dy.*t5.*(-1.0./2.0e+1),dq1.*t2.*(-1.0./2.0e+1),0.0],[4,4]);
