function W_X_B = get_W_X_B(in1)
%get_W_X_B
%    W_X_B = get_W_X_B(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    30-Nov-2023 14:58:03

x = in1(1,:);
y = in1(2,:);
W_X_B = reshape([1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,x,y,0.0,1.0],[4,4]);
