function out1 = get_world_com(in1)
%GET_WORLD_COM
%    OUT1 = GET_WORLD_COM(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    30-Nov-2023 14:58:02

q1 = in1(3,:);
q2 = in1(4,:);
x = in1(1,:);
y = in1(2,:);
t2 = q1+q2;
out1 = [x+cos(q1)./1.6e+2+cos(t2)./4.8e+2;y+sin(q1)./1.6e+2+sin(t2)./4.8e+2];
