function M = get_M(in1)
%get_M
%    M = get_M(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    30-Nov-2023 14:58:04

q1 = in1(3,:);
q2 = in1(4,:);
t2 = cos(q1);
t3 = cos(q2);
t4 = sin(q1);
t5 = q1+q2;
t6 = cos(t5);
t7 = sin(t5);
t8 = t3./4.0e+1;
t9 = t2.*(3.0./4.0e+1);
t10 = t4.*(3.0./4.0e+1);
t11 = -t10;
t12 = t6./4.0e+1;
t13 = t7./4.0e+1;
t17 = t8+1.669333333333333e-2;
t14 = -t13;
t15 = t9+t12;
t16 = t11+t14;
M = reshape([1.2e+1,0.0,t16,t14,0.0,1.2e+1,t15,t12,t16,t15,t3./2.0e+1+8.338666666666667e-2,t17,t14,t12,t17,1.669333333333333e-2],[4,4]);
