function out1 = get_J_v_LL(in1)
%get_J_v_LL
%    OUT1 = get_J_v_LL(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    30-Nov-2023 14:58:03

q1 = in1(3,:);
q2 = in1(4,:);
t2 = q1+q2;
t3 = cos(t2);
t4 = sin(t2);
t5 = t3./2.0;
t6 = t4./2.0;
t7 = -t6;
out1 = reshape([1.0,0.0,0.0,1.0,t7-sin(q1),t5+cos(q1),t7,t5],[2,4]);
