function J_s = get_J_s(in1)
%get_J_s
%    J_s = get_J_s(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    02-Feb-2023 02:40:50

q1 = in1(3,:);
q2 = in1(4,:);
t2 = q1+q2;
t3 = cos(t2);
t4 = sin(t2);
t5 = t3.*(4.0./2.5e+1);
t6 = t4.*(4.0./2.5e+1);
t7 = -t6;
J_s = reshape([0.0,0.0,0.0,0.0,t7-sin(q1).*(4.0./2.5e+1),t5+cos(q1).*(4.0./2.5e+1),t7,t5],[2,4]);
