function foot_pos = get_foot_pos(in1)
%GET_FOOT_POS
%    FOOT_POS = GET_FOOT_POS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    30-Nov-2023 14:58:03

q1 = in1(3,:);
q2 = in1(4,:);
t2 = cos(q1);
t3 = cos(q2);
t4 = sin(q1);
t5 = sin(q2);
t6 = t3./2.0;
t7 = t6+1.0./2.0;
foot_pos = [t2./2.0+t2.*t6+t2.*t7-t4.*t5;t4./2.0+t2.*t5+t4.*t6+t4.*t7];
