function J_c_dot = get_J_c_dot(in1)
%get_J_c_dot
%    J_c_dot = get_J_c_dot(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    30-Nov-2023 14:58:07

dq1 = in1(7,:);
dq2 = in1(8,:);
q1 = in1(3,:);
q2 = in1(4,:);
t2 = dq1+dq2;
t3 = q1+q2;
t4 = cos(t3);
t5 = sin(t3);
J_c_dot = reshape([0.0,0.0,0.0,0.0,-dq2.*t4-dq1.*(t4+cos(q1)),-dq2.*t5-dq1.*(t5+sin(q1)),-t2.*t4,-t2.*t5],[2,4]);
