function G = get_G(in1)
%get_G
%    G = get_G(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    30-Nov-2023 14:58:04

q1 = in1(3,:);
q2 = in1(4,:);
t2 = q1+q2;
t3 = cos(t2);
t4 = t3.*2.4525e-1;
G = [0.0;1.1772e+2;t4+cos(q1).*7.3575e-1;t4];
