function out1 = get_J_v_B
%get_J_v_B
%    OUT1 = get_J_v_B

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    30-Nov-2023 14:58:03

out1 = reshape([1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0],[2,4]);
