function W_X_UL = get_W_X_UL(in1)
%get_W_X_UL
%    W_X_UL = get_W_X_UL(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    30-Nov-2023 14:58:03

q1 = in1(3,:);
x = in1(1,:);
y = in1(2,:);
t2 = cos(q1);
t3 = sin(q1);
W_X_UL = reshape([t2,t3,0.0,0.0,-t3,t2,0.0,0.0,0.0,0.0,1.0,0.0,t2./2.0+x,t3./2.0+y,0.0,1.0],[4,4]);
